//
// Created by nikita on 08.10.2026.
//

#ifndef MYCOOLGAMEENGINE_HANDS_ACTION_PRIORITIES_H
#define MYCOOLGAMEENGINE_HANDS_ACTION_PRIORITIES_H

#define HANDS_ACTION_PRIORITY_PHYS_ATTACK 0
#define HANDS_ACTION_PRIORITY_INTERRUPTIBLE_SKILL 1
#define HANDS_ACTION_PRIORITY_MOVEMENT 2
#define HANDS_ACTION_UNINTERRUPTIBLE_SKILL 3

#endif //MYCOOLGAMEENGINE_HANDS_ACTION_PRIORITIES_H
