//
// Created by nikita on 08.10.2026.
//

#ifndef MYCOOLGAMEENGINE_HANDS_ACTION_PRIORITIES_H
#define MYCOOLGAMEENGINE_HANDS_ACTION_PRIORITIES_H

#define HANDS_ACTION_PRIORITY_MOVEMENT 10

#endif //MYCOOLGAMEENGINE_HANDS_ACTION_PRIORITIES_H
