//
// Created by nikita on 22.09.2026.
//

#ifndef MYCOOLGAMEENGINE_VERSION_H
#define MYCOOLGAMEENGINE_VERSION_H

#define VERSION_MAJOR 0
#define VERSION_MINOR 1
#define VERSION_PATCH 3

#endif //MYCOOLGAMEENGINE_VERSION_H
