//
// Created by nikita on 22.09.2026.
//

#ifndef MYCOOLGAMEENGINE_VERSION_H
#define MYCOOLGAMEENGINE_VERSION_H

#define ENGINE_V_MAJOR 0
#define ENGINE_V_MINOR 3
#define ENGINE_V_PATCH 4

#endif //MYCOOLGAMEENGINE_VERSION_H
