//
// Created by nikita on 03.10.2026.
//

#ifndef MYCOOLGAMEENGINE_VERSION_H
#define MYCOOLGAMEENGINE_VERSION_H

#define DEMO_V_MAJOR 0
#define DEMO_V_MINOR 0
#define DEMO_V_PATCH 4

#endif //MYCOOLGAMEENGINE_VERSION_H
